//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mauiapp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mauiapp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera access is required to take pictures..
        /// </summary>
        internal static string CameraAccessIsRequiredToTakePictures {
            get {
                return ResourceManager.GetString("CameraAccessIsRequiredToTakePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not found..
        /// </summary>
        internal static string CameraNotFound {
            get {
                return ResourceManager.GetString("CameraNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Device:.
        /// </summary>
        internal static string DeviceSelection {
            get {
                return ResourceManager.GetString("DeviceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the camera: .
        /// </summary>
        internal static string FailedToStartTheCamera {
            get {
                return ResourceManager.GetString("FailedToStartTheCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Caption.
        /// </summary>
        internal static string ImageCaption {
            get {
                return ResourceManager.GetString("ImageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image caption was not found in the specified time range..
        /// </summary>
        internal static string ImgCaptionNotFound {
            get {
                return ResourceManager.GetString("ImgCaptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP is null. Please set one..
        /// </summary>
        internal static string IpNull {
            get {
                return ResourceManager.GetString("IpNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Set..
        /// </summary>
        internal static string IPSet {
            get {
                return ResourceManager.GetString("IPSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP Address was succesfully set..
        /// </summary>
        internal static string IpSuccess {
            get {
                return ResourceManager.GetString("IpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cameras found..
        /// </summary>
        internal static string NoCamerasFound {
            get {
                return ResourceManager.GetString("NoCamerasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP is null, or invalid. Please assign a real IP to the program via the Preferences tab..
        /// </summary>
        internal static string NullInvalidIP {
            get {
                return ResourceManager.GetString("NullInvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re Offline..
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non si tratta di essere i migliori, ma di essere migliori di ieri. Entra, allenati, supera i tuoi limiti!.
        /// </summary>
        internal static string quote {
            get {
                return ResourceManager.GetString("quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Camera: .
        /// </summary>
        internal static string SelectedCamera {
            get {
                return ResourceManager.GetString("SelectedCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Camera..
        /// </summary>
        internal static string SetCamera {
            get {
                return ResourceManager.GetString("SetCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your IP..
        /// </summary>
        internal static string SetIP {
            get {
                return ResourceManager.GetString("SetIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Picture.
        /// </summary>
        internal static string TakeAPicture {
            get {
                return ResourceManager.GetString("TakeAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading Error!.
        /// </summary>
        internal static string UploadingError {
            get {
                return ResourceManager.GetString("UploadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Status.
        /// </summary>
        internal static string UploadStatus {
            get {
                return ResourceManager.GetString("UploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your caption wasn&apos;t found..
        /// </summary>
        internal static string YourCaptionWasnTFound {
            get {
                return ResourceManager.GetString("YourCaptionWasnTFound", resourceCulture);
            }
        }
    }
}
