name: .NET Core Desktop and Android

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: mauiapp1.sln
      Android_Project_Path: ./mauiapp1.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Execute unit tests
      run: dotnet test

    - name: Restore the application
      run: dotnet restore $env:Solution_Name

    # Publish Windows EXE
    - name: Publish Windows EXE
      run: dotnet publish $env:Solution_Name -r win10-x64 -f net8.0-windows10.0.19041.0 -c ${{ matrix.configuration }} -p:PublishSingleFile=true -p:SelfContained=true -o publish-output

    # Build Android APK
    - name: Build Android APK
      run: |
        dotnet publish $env:Android_Project_Path -c ${{ matrix.configuration }} -r android-arm64 --self-contained true -o apk-output

    # Upload build artifacts
    - name: Upload Windows EXE
      uses: actions/upload-artifact@v4
      with:
        name: Windows EXE
        path: publish-output/

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: Android APK
        path: apk-output/
